### ISSUE TITLE
onPress is passed to Animated.View while dragging

### ISSUE THREAD

**Issue by iremlopsum** [wix/react-native-interactable#30]
Sliding between Slides still passes an onPress to the child view.

I have a button, and if I drag from it, it gets pressed. Any idea how to solve this reasonably and show that I wouldn't have to handle it on every button separately? To specify, I released the mouse myself and onPressed wasn't passed while I was dragging, but upon release of of drag.

![slidingandpress](https://cloud.githubusercontent.com/assets/8178748/24126356/cb4942dc-0d8a-11e7-959c-02dab46020e4.gif)

**Comment by talkol** [comment]
If I'm not mistaken, this is an Android only issue. also referenced at #31 

On iOS it should be working nicely, you can test the following in the example app:
https://github.com/wix/react-native-interactable/blob/master/example/src/TouchesInside.js

@LoyalBlocks-tzachi will work on the touches in Android starting Sunday. If anyone wants to fix them beforehand, we'll appreciate it

**Comment by iremlopsum** [comment]
@talkol that's cool. As well I noticed that I can't scroll with in an Animated.View. Seems that interactable is hijacking the event. Does this fall under the same issue?

**Comment by talkol** [comment]
I think so, I just tested a webview that scrolls in both directions inside an interactable.view and it works well on iOS (it's the same test I linked above)

**Comment by Ehesp** [comment]
@iremlopsum I raised the scrolling issue here, then saw this issue sorry! https://github.com/wix/react-native-interactable/issues/35

**Comment by LoyalBlocks-tzachi** [comment]
Hi guys! I fixed most of the Android touch issues in this branch: https://github.com/wix/react-native-interactable/tree/androidFixes

I'll appreciate if you can give feedback before I merge to master

The issue that still remains unresolved (I'm still working on it) is horizontal scroll inside horizontal moving interactable (or anything with horizontal drag like a slider)

**Comment by talkol** [comment]
Merged into master (v0.0.7). Please re-open if the issue is still there. Should be resolved.

**Comment by victorileaf** [comment]
@talkol Hi, Android touch is still present in the latest version. can some one help me? Im not getting onPress events Refer: https://github.com/wix/react-native-interactable/issues/187
